PREFIX fx: <http://sparql.xyz/facade-x/ns/>
PREFIX xyz: <http://sparql.xyz/facade-x/data/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
CONSTRUCT {?s ?p ?o} WHERE {

  service <x-sparql-anything:spreadsheet.evaluate-formulas=true>
  {
    fx:properties fx:location "%%%LOCATION%%%" .
    ?s ?p ?o
  }

}