PREFIX  fx:   <http://sparql.xyz/facade-x/ns/>
PREFIX  rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX  xyz:  <http://sparql.xyz/facade-x/data/>

SELECT  *
WHERE
  { SERVICE <x-sparql-anything:>
      { 
		SERVICE <x-sparql-anything:>
          { fx:properties
                      fx:command     "echo 4,5,6" ;
                      fx:media-type  "text/csv" .
            ?s       a fx:root ; rdf:_1/fx:anySlot            ?num .
            # ?s  ?p ?num # breaks!
            # BIND(bnode() AS ?bob)           # breaks
            # BIND(struuid() AS ?bob)         # breaks
            # BIND(concat("a","b") AS ?bob)   # works
            # BIND("lala" AS ?bob)            # works
        }
        
		BIND(concat("seq ", ?num) AS ?second_cmd)
        
		fx:properties
                  fx:command     ?second_cmd ;
                  fx:media-type  "text/plain" ;
                  fx:txt.split   "\n" .
		
        ?ss       ?pp            ?oo
      }
  }