PREFIX fx: <http://sparql.xyz/facade-x/ns/>
PREFIX xyz: <http://sparql.xyz/facade-x/data/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT * WHERE {
  SERVICE <x-sparql-anything:spreadsheet.evaluate-formulas=true> {
    fx:properties fx:location "%%%LOCATION%%%" .
          [] rdf:type fx:root ;
             fx:anySlot ?row .
          ?row rdf:_1 ?n .
          ?row rdf:_2 ?now

    SERVICE <x-sparql-anything:> {


       fx:properties fx:content "[1.0,2.0,3.0]" .
               fx:properties fx:media-type "application/json" .
               ?s fx:anySlot ?n .
    }


  }
}